eval(File.read(File.dirname(__FILE__) + '/../common_spree_dependencies.rb'))

gem 'spree_core', path: '../core'
gem 'spree_api', path: '../api'
gem 'spree_multi_vendor', github: 'spree-contrib/spree_multi_vendor'

gemspec
